spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssacation?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: ssafy123
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true # API 명세 그룹화
  swagger-ui:
    operations-sorter: alpha # 정렬 방식
    # alpha (알파벳 오름차순)
    # method (HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # Swagger 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag와 operation 펼치는 방식
  paths-to-match:
    - /** # 일치하는 경로의 API만 제공